config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'city/:id', to: 'city#show', as: 'city'
  #get 'gossips/:id', to: 'gossips#show', as: 'gossips
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :gossips
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true
	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_secure_password

  validates :email,
    presence: true
    #format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @city.users.each do |u|
      @goss = u.gossips
    end
    # @goss.each do |g|
    #   @user_city_gossips = g.content
    # end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
     if @gossip.save
      flash[:notice] = "Nouveau Gossip créé"
       redirect_to root_path
     else
       flash[:error] = "Mauvais input"
       render 'new'
     end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params =  params.permit(:title, :content)
    if  @gossip.update(gossip_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
  # cherche s'il existe un utilisateur en base avec l’e-mail
  user = User.find_by(email: params[:email])

  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    # redirige où tu veux, avec un flash ou pas
    redirect_to root_path

  else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end


  def new
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
    @gossip = Gossip.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(email: params[:email], password: params[:password],first_name: params[:first_name], last_name: params[:last_name], description: params[:description], age: params[:age], city_id: City.all.sample.id)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
        puts "Voici le message de l'URL :"
        puts  params[:user_entry]
        puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<div class="card">
  <div class="card-header">
    <h1><u>Ville # <%= params[:id] %></u></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Nom : <%= @city.name %></h5>
  </div>
<div class="card-footer"><h2><u>Potins:</u></h2><% @goss.each do |gossip| %>
<blockquote class="blockquote font-italic">"<%= gossip.content %>"</blockquote>
<%end%></div>
</div>

app/views/gossips/edit.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">title</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>















      <div class="card border-info m-5">
       <div class="card-header"><h1><i class="fas fa-edit"></i> Édite le potin n° <%= params[:id] %></h1></div>

        <%= form_tag url_for(action: 'update'), method: "patch" do %>

            <div class="card-body text-info">
              <div class="form-group">
                <%= label_tag 'Titre'%>
                <%= text_field_tag :title, @gossip.title, class:'form-control', placeholder: @gossip.title %>
                <br /> <br />

                <%= label_tag 'Contenu du potin' %>
                <%= text_area_tag :content, @gossip.content, class:'form-control', placeholder: @gossip.content %>
                <br /> <br />

                <%= submit_tag "Éditer le potin", class: "btn btn-info" %>
              <% end %>
            </div>
          </div>


        </div>
      </div>

app/views/gossips/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>

    <%= label_tag 'Title' %>
    <%= text_field_tag :title, @gossip.title, class: "form-control", placeholder: "Comming out" %>
    <br /> <br />

    <%= label_tag 'Content' %>
    <%= text_area_tag :content, @gossip.content, class: "form-control", placeholder: "I'm gay as fuck"  %>
    <br /> <br />
    <%= submit_tag "Create Post", class: "btn btn-primary" %>

  <% end %>

  <!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form> -->

  <% if flash[:notice]%>
  <div class="alert alert-success">Nouveau gossip créé</div>
  <%end%>

  <% if flash[:error]%>
  <div class="alert alert-danger">tu as oublié le titre du gossip</div>
  <%end%>

app/views/gossips/show.html.erb
<div class="card">
  <div class="card-header">
    <h1><u>Gossip # <%= params[:id] %></u></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Titre : <%= @gossip.title %></h5>
    <h5 class="card-text">Gossip : "<%= @gossip.content %>"</h5>
    <h5>Date de création : <%= @gossip.created_at %></h5>
    <%= link_to "Editer le Potin", edit_gossip_path(params[:id])%>
    <a href="<%gossip_path(@gossip.id)%>" class="btn btn-danger" data-confirm="êtes-vous sur ?" data-method="DELETE">Supprimer</a>
  </div>
</div>
<div class="card">
  <div class="card-header">
    <h1><u><%= @gossip.user.first_name %></u></h1>
  </div>
  <div class="card-body">
      <h5><%= link_to "Ville :", city_path(@gossip.user.city_id) %> <%= @gossip.user.city.name %></h5>
    <%= link_to "Page Auteur", user_path(@gossip.user.id), :class => "btn-info btn" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Créer son compte</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div class="card-body text-info">
      <div class="form-group">
        <%= text_field_tag 'first_name', '', class: "form-control", placeholder: "Prénom" %>
        <%= text_field_tag 'last_name', '', class: "form-control", placeholder: "Nom" %>
        <%= text_field_tag 'description', '', class: "form-control", placeholder: "Description" %>
        <%= text_field_tag 'age', '', class: "form-control", placeholder: "Âge" %>
        <%= text_field_tag 'email', '', class: "form-control", placeholder: "Email" %>
        <%= password_field_tag 'password', '', class: "form-control", placeholder: "Mot de passe" %>
        <br /> <br />
        <%= submit_tag "Je m'inscris !", class: "btn btn-info" %>
      <p class="mt-4">Déjà un compte ? <%= link_to "Je me connecte !", new_session_path %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="card border-info">
  <div class="card-header">
    <h1><u><%= @user.first_name + " " + @user.last_name  %></u></h1>
  </div>
  <div class="card-body text-info">
    <ul class="card-text">
      <li>Prénom : <%= @user.first_name %></li>
      <li>Nom : <%= @user.last_name %></li>
      <li>Email : <%= @user.email %></li>
      <li>Bio : <%= @user.description %></li>
      <li>Âge : <%= @user.age %></li>
      <li><%= link_to "Ville :", city_path(@user.city_id) %> <%= @user.city.name %></li>
    </ul>
  </div>
  <div class="card-footer"><h2><u>Potins:</u></h2><% @user.gossips.each do |i| %>
  <blockquote class="blockquote font-italic">"<%= i.content %>"</blockquote>
  <%end%></div>
</div>