config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'city/:id', to: 'city#show', as: 'city'
  #get 'gossips/:id', to: 'gossips#show', as: 'gossips
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :gossips
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true
	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_secure_password

  validates :email,
    presence: true
    #format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @city.users.each do |u|
      @goss = u.gossips
    end
    # @goss.each do |g|
    #   @user_city_gossips = g.content
    # end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
     if @gossip.save
      flash[:notice] = "Nouveau Gossip créé"
       redirect_to root_path
     else
       flash[:error] = "Mauvais input"
       render 'new'
     end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params =  params.permit(:title, :content)
    if  @gossip.update(gossip_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(email: params[:email], password: params[:password],first_name: params[:first_name], last_name: params[:last_name], description: params[:description], age: params[:age], city_id: City.all.sample.id)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
        puts "Voici le message de l'URL :"
        puts  params[:user_entry]
        puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- css bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body">

    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "The Potin Project", root_path, :class => "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Contact", contact_path, :class => "nav-item", :class => "nav-link" %>
          <%= link_to "Team", team_path, :class => "nav-item nav-link" %>
          <%= link_to "Nouveau Potin", new_gossip_path, :class => "nav-item", :class => "nav-link" %>
          <%= link_to "Login", new_session_path, :class => "btn-info btn" %>
          <%= link_to "Disconnect", new_session_path, :class => "btn-danger btn" %>
        </div>
      </div>
    </nav>

  <div class= "ml-2 mt-2" >
    <%= yield %>
  </div>
  </body>
</html>